version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:18
    working_dir: /usr/src/servico-news
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    environment:
      - MONGO_URL=mongodb://mongo:27017/servico-news
    volumes:
      - ./dist/:/usr/src/servico-news/dist
      - ./package.json:/usr/src/servico-news/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo
